"""CSV fieldnames for PO ShipStation order export."""

from __future__ import annotations

CSV_FIELDNAMES = [
    "orderNumber",
    "advancedOptions billToAccount",
    "advancedOptions billToCountryCode",
    "advancedOptions billToMyOtherAccount",
    "advancedOptions billToParty",
    "advancedOptions billToPostalCode",
    "advancedOptions containsAlcohol",
    "advancedOptions customField1",
    "advancedOptions customField2",
    "advancedOptions customField3",
    "advancedOptions mergedOrSplit",
    "advancedOptions nonMachinable",
    "advancedOptions parentId",
    "advancedOptions saturdayDelivery",
    "advancedOptions source",
    "advancedOptions storeId",
    "advancedOptions warehouseId",
    "amountPaid",
    "basic sku",
    "billTo addressVerified",
    "billTo city",
    "billTo company",
    "billTo country",
    "billTo name",
    "billTo phone",
    "billTo postalCode",
    "billTo residential",
    "billTo state",
    "billTo street1",
    "billTo street2",
    "billTo street3",
    "carrierCode",
    "confirmation",
    "createDate",
    "customerEmail",
    "customerId",
    "customerNotes",
    "customerUsername",
    "dimensions",
    "dimensions height",
    "dimensions length",
    "dimensions units",
    "dimensions width",
    "externallyFulfilled",
    "externallyFulfilledBy",
    "externallyFulfilledById",
    "externallyFulfilledByName",
    "gift",
    "giftMessage",
    "holdUntilDate",
    "insuranceOptions insureShipment",
    "insuranceOptions insuredValue",
    "insuranceOptions provider",
    "internalNotes",
    "internationalOptions contents",
    "internationalOptions customsItems",
    "internationalOptions nonDelivery",
    "item 0 option 0 name",
    "item 0 option 0 value",
    "item 0 option 1 name",
    "item 0 option 1 value",
    "item 0 option 2 name",
    "item 0 option 2 value",
    "items 0 adjustment",
    "items 0 createDate",
    "items 0 fulfillmentSku",
    "items 0 imageUrl",
    "items 0 lineItemKey",
    "items 0 modifyDate",
    "items 0 name",
    "items 0 orderItemId",
    "items 0 productId",
    "items 0 quantity",
    "items 0 shippingAmount",
    "items 0 sku",
    "items 0 taxAmount",
    "items 0 unitPrice",
    "items 0 upc",
    "items 0 warehouseLocation",
    "items 0 weight",
    "labelMessages",
    "modifyDate",
    "orderDate",
    "orderId",
    "orderKey",
    "orderStatus",
    "orderTotal",
    "packageCode",
    "paymentDate",
    "paymentMethod",
    "requestedShippingService",
    "serviceCode",
    "shipByDate",
    "shipDate",
    "shipTo addressVerified",
    "shipTo city",
    "shipTo company",
    "shipTo country",
    "shipTo name",
    "shipTo phone",
    "shipTo postalCode",
    "shipTo residential",
    "shipTo state",
    "shipTo street1",
    "shipTo street2",
    "shipTo street3",
    "shippingAmount",
    "tagIds",
    "taxAmount",
    "userId",
    "weight WeightUnits",
    "weight units",
    "weight value",
]
