from scripts.pipeline_generate_packing_list_pdf.pdf_page_layout import (
    B0_Y_PT,
    B1_Y_PT,
    BANNER_H_PT,
    BLACK,
    BOX_PAD_X_PT,
    BOX_PAD_Y_PT,
    COL_W_PT,
    CONTENT_H_PT,
    FONT_SIZE_BANNER,
    FONT_SIZE_ITEM_NAME,
    FONT_SIZE_LEFT_LABEL,
    FONT_SIZE_POSITION,
    FONT_SIZE_TOP,
    HEADER_PAD_PT,
    HEADER_TOP_PAD_PT,
    IMAGE_AREA_W_PT,
    IMAGE_AREA_X_PT,
    IMAGE_X,
    LEFT_COLOUR_TOP_PT,
    LEFT_FOUR_TOP_PT,
    LEFT_GENDER_CELL_H_PT,
    LEFT_ITEM_QTY_TOP_PT,
    LEFT_OTHER_CELL_H_PT,
    LEFT_SIZE_TOP_PT,
    LEFT_W,
    LEFT_W_PT,
    LEFT_X,
    RECIPIENT_H_PT,
    RED,
    S1_Y_PT,
    S2_SQUARE_H_PT,
    S2_Y_PT,
    SCALE_W,
    SQUARE_S_PT,
    TOP_H_PT,
    WHITE,
    pt_h as _pt_h,
    pt_w as _pt_w,
    rl_y as _rl_y,
)


def build_draw_page_static_args_impl(
    *,
    default_position_code,
    image_reader_cls,
    draw_blocks,
    draw_page_header_left,
    draw_left_bottom_item_image,
    resolve_custom_logo_context,
    draw_position_banners,
    draw_apparel_square,
    logo_image_for_slot,
    draw_logo_overlays,
    draw_logo_square_rows,
    safe_str,
    logo_design_tokens,
    normalize_lower,
    find_image_custom_exact,
    find_image_custom_logo,
    find_image_normal_logo,
    find_image_custom_fbpi,
    find_image,
    prepare_image_from_url,
    prepare_image,
    rect_at,
    draw_text_in_box,
    draw_text_in_padded_box,
    draw_recipient_name_in_box,
    draw_rect,
    get_field_value,
    parse_process_and_item,
    position_tokens,
):
    return {
        "top_h_pt": TOP_H_PT,
        "content_h_pt": CONTENT_H_PT,
        "image_area_x_pt": IMAGE_AREA_X_PT,
        "image_x": IMAGE_X,
        "image_area_w_pt": IMAGE_AREA_W_PT,
        "left_x": LEFT_X,
        "left_w": LEFT_W,
        "left_w_pt": LEFT_W_PT,
        "left_four_top_pt": LEFT_FOUR_TOP_PT,
        "left_gender_cell_h_pt": LEFT_GENDER_CELL_H_PT,
        "left_size_top_pt": LEFT_SIZE_TOP_PT,
        "left_colour_top_pt": LEFT_COLOUR_TOP_PT,
        "left_item_qty_top_pt": LEFT_ITEM_QTY_TOP_PT,
        "left_other_cell_h_pt": LEFT_OTHER_CELL_H_PT,
        "recipient_h_pt": RECIPIENT_H_PT,
        "s1_y_pt": S1_Y_PT,
        "s2_y_pt": S2_Y_PT,
        "b0_y_pt": B0_Y_PT,
        "b1_y_pt": B1_Y_PT,
        "col_w_pt": COL_W_PT,
        "square_s_pt": SQUARE_S_PT,
        "s2_square_h_pt": S2_SQUARE_H_PT,
        "banner_h_pt": BANNER_H_PT,
        "scale_w": SCALE_W,
        "header_pad_pt": HEADER_PAD_PT,
        "header_top_pad_pt": HEADER_TOP_PAD_PT,
        "box_pad_x_pt": BOX_PAD_X_PT,
        "box_pad_y_pt": BOX_PAD_Y_PT,
        "font_size_top": FONT_SIZE_TOP,
        "font_size_item_name": FONT_SIZE_ITEM_NAME,
        "font_size_left_label": FONT_SIZE_LEFT_LABEL,
        "font_size_position": FONT_SIZE_POSITION,
        "font_size_banner": FONT_SIZE_BANNER,
        "default_position_code": default_position_code,
        "black": BLACK,
        "red": RED,
        "white": WHITE,
        "draw_blocks": draw_blocks,
        "draw_page_header_left": draw_page_header_left,
        "draw_left_bottom_item_image": draw_left_bottom_item_image,
        "resolve_custom_logo_context": resolve_custom_logo_context,
        "draw_position_banners": draw_position_banners,
        "draw_apparel_square": draw_apparel_square,
        "logo_image_for_slot": logo_image_for_slot,
        "draw_logo_overlays": draw_logo_overlays,
        "draw_logo_square_rows": draw_logo_square_rows,
        "safe_str": safe_str,
        "logo_design_tokens": logo_design_tokens,
        "normalize_lower": normalize_lower,
        "find_image_custom_exact": find_image_custom_exact,
        "find_image_custom_logo": find_image_custom_logo,
        "find_image_normal_logo": find_image_normal_logo,
        "find_image_custom_fbpi": find_image_custom_fbpi,
        "find_image": find_image,
        "prepare_image_from_url": prepare_image_from_url,
        "prepare_image": prepare_image,
        "rect_at": rect_at,
        "draw_text_in_box": draw_text_in_box,
        "draw_text_in_padded_box": draw_text_in_padded_box,
        "draw_recipient_name_in_box": draw_recipient_name_in_box,
        "draw_rect": draw_rect,
        "get_field_value": get_field_value,
        "parse_process_and_item": parse_process_and_item,
        "position_tokens": position_tokens,
        "pt_w": _pt_w,
        "pt_h": _pt_h,
        "rl_y": _rl_y,
        "image_reader_cls": image_reader_cls,
    }
