from pathlib import Path
from typing import Callable, Dict, Optional, Tuple

from scripts.pipeline_generate_packing_list_pdf.draw_page_finalize import (
    finalize_logo_sections_impl,
)
from scripts.pipeline_generate_packing_list_pdf.draw_page_logo_suffix_labels_step import (
    run_logo_filename_suffix_label_step_impl,
)
from scripts.pipeline_generate_packing_list_pdf.draw_page_setup import (
    prepare_draw_page_state_impl,
)

def draw_page_impl(
    c,
    row_series,
    order_number_counts: dict,
    process_totals: Optional[Dict[str, int]],
    *,
    apparel_image_dir: Optional[Path],
    logo_customise_dir: Optional[Path],
    logo_normal_dir: Optional[Path],
    apparel_stem_map: Optional[Dict[str, Path]],
    logo_custom_stem_map: Optional[Dict[str, Path]],
    logo_normal_stem_map: Optional[Dict[str, Path]],
    position_code_to_draw: Optional[Dict[str, str]],
    top_h_pt: float,
    content_h_pt: float,
    image_area_x_pt: float,
    image_x: float,
    image_area_w_pt: float,
    left_x: float,
    left_w: float,
    left_w_pt: float,
    left_four_top_pt: float,
    left_gender_cell_h_pt: float,
    left_size_top_pt: float,
    left_colour_top_pt: float,
    left_item_qty_top_pt: float,
    left_other_cell_h_pt: float,
    recipient_h_pt: float,
    s1_y_pt: float,
    s2_y_pt: float,
    b0_y_pt: float,
    b1_y_pt: float,
    col_w_pt: float,
    square_s_pt: float,
    s2_square_h_pt: float,
    banner_h_pt: float,
    scale_w: float,
    header_pad_pt: float,
    header_top_pad_pt: float,
    box_pad_x_pt: float,
    box_pad_y_pt: float,
    font_size_top: float,
    font_size_item_name: float,
    font_size_left_label: float,
    font_size_position: float,
    font_size_banner: float,
    default_position_code: str,
    black,
    red,
    white,
    draw_blocks,
    draw_page_header_left,
    draw_left_bottom_item_image,
    resolve_custom_logo_context,
    draw_position_banners,
    draw_apparel_square,
    logo_image_for_slot,
    draw_logo_overlays,
    draw_logo_square_rows,
    safe_str,
    logo_design_tokens,
    normalize_lower,
    find_image_custom_exact,
    find_image_custom_logo,
    find_image_normal_logo,
    find_image_custom_fbpi,
    find_image,
    prepare_image_from_url,
    prepare_image,
    rect_at,
    draw_text_in_box,
    draw_text_in_padded_box,
    draw_recipient_name_in_box,
    draw_rect,
    get_field_value,
    parse_process_and_item,
    position_tokens,
    pt_w,
    pt_h,
    rl_y,
    image_reader_cls,
    pdf_asset_log: Optional[Callable[[str], None]] = None,
    pdf_page_index: int = 0,
    dispatch_date_label: Optional[str] = None,
    dispatch_day_name: Optional[str] = None,
) -> tuple[bool, bool]:
    had_missing_logo = False
    had_missing_apparel = False
    (
        is_plain_order,
        is_scoped_custom_merge,
        base_custom_path,
        fbpi_slots,
        position_has_slash,
        ax,
        ay,
        aw,
        ah,
        had_missing_apparel_local,
    ) = prepare_draw_page_state_impl(
        c,
        row_series,
        order_number_counts,
        process_totals,
        top_h_pt=top_h_pt,
        left_x=left_x,
        left_w=left_w,
        image_x=image_x,
        image_area_w_pt=image_area_w_pt,
        scale_w=scale_w,
        header_pad_pt=header_pad_pt,
        header_top_pad_pt=header_top_pad_pt,
        font_size_top=font_size_top,
        font_size_item_name=font_size_item_name,
        font_size_left_label=font_size_left_label,
        recipient_h_pt=recipient_h_pt,
        left_w_pt=left_w_pt,
        box_pad_x_pt=box_pad_x_pt,
        box_pad_y_pt=box_pad_y_pt,
        left_four_top_pt=left_four_top_pt,
        left_gender_cell_h_pt=left_gender_cell_h_pt,
        left_size_top_pt=left_size_top_pt,
        left_colour_top_pt=left_colour_top_pt,
        left_item_qty_top_pt=left_item_qty_top_pt,
        left_other_cell_h_pt=left_other_cell_h_pt,
        content_h_pt=content_h_pt,
        s2_y_pt=s2_y_pt,
        default_position_code=default_position_code,
        image_area_x_pt=image_area_x_pt,
        col_w_pt=col_w_pt,
        b0_y_pt=b0_y_pt,
        b1_y_pt=b1_y_pt,
        banner_h_pt=banner_h_pt,
        font_size_position=font_size_position,
        white=white,
        s1_y_pt=s1_y_pt,
        square_s_pt=square_s_pt,
        font_size_banner=font_size_banner,
        black=black,
        red=red,
        logo_customise_dir=logo_customise_dir,
        logo_custom_stem_map=logo_custom_stem_map,
        position_code_to_draw=position_code_to_draw,
        apparel_image_dir=apparel_image_dir,
        apparel_stem_map=apparel_stem_map,
        safe_str=safe_str,
        pt_h=pt_h,
        rl_y=rl_y,
        draw_blocks=draw_blocks,
        draw_page_header_left=draw_page_header_left,
        draw_left_bottom_item_image=draw_left_bottom_item_image,
        resolve_custom_logo_context=resolve_custom_logo_context,
        draw_position_banners=draw_position_banners,
        draw_apparel_square=draw_apparel_square,
        rect_at=rect_at,
        draw_text_in_box=draw_text_in_box,
        draw_text_in_padded_box=draw_text_in_padded_box,
        draw_recipient_name_in_box=draw_recipient_name_in_box,
        draw_rect=draw_rect,
        get_field_value=get_field_value,
        parse_process_and_item=parse_process_and_item,
        pt_w=pt_w,
        prepare_image_from_url=prepare_image_from_url,
        image_reader_cls=image_reader_cls,
        logo_design_tokens=logo_design_tokens,
        find_image_custom_exact=find_image_custom_exact,
        find_image_custom_logo=find_image_custom_logo,
        find_image_custom_fbpi=find_image_custom_fbpi,
        position_tokens=position_tokens,
        find_image=find_image,
        prepare_image=prepare_image,
        pdf_asset_log=pdf_asset_log,
        pdf_page_index=pdf_page_index,
        dispatch_date_label=dispatch_date_label,
        dispatch_day_name=dispatch_day_name,
    )
    had_missing_apparel = had_missing_apparel or had_missing_apparel_local

    had_missing_logo = had_missing_logo or finalize_logo_sections_impl(
        c,
        row_series,
        order_number_counts,
        fbpi_slots=fbpi_slots,
        base_custom_path=base_custom_path,
        is_scoped_custom_merge=is_scoped_custom_merge,
        logo_customise_dir=logo_customise_dir,
        logo_custom_stem_map=logo_custom_stem_map,
        logo_normal_dir=logo_normal_dir,
        logo_normal_stem_map=logo_normal_stem_map,
        position_has_slash=position_has_slash,
        position_code_to_draw=position_code_to_draw,
        default_position_code=default_position_code,
        position_tokens=position_tokens,
        ax=ax,
        ay=ay,
        aw=aw,
        ah=ah,
        is_plain_order=is_plain_order,
        image_area_x_pt=image_area_x_pt,
        col_w_pt=col_w_pt,
        s1_y_pt=s1_y_pt,
        s2_y_pt=s2_y_pt,
        square_s_pt=square_s_pt,
        s2_square_h_pt=s2_square_h_pt,
        font_size_banner=font_size_banner,
        black=black,
        red=red,
        logo_image_for_slot=logo_image_for_slot,
        draw_logo_overlays=draw_logo_overlays,
        draw_logo_square_rows=draw_logo_square_rows,
        safe_str=safe_str,
        logo_design_tokens=logo_design_tokens,
        normalize_lower=normalize_lower,
        find_image_custom_exact=find_image_custom_exact,
        find_image_custom_logo=find_image_custom_logo,
        find_image_normal_logo=find_image_normal_logo,
        prepare_image=prepare_image,
        rect_at=rect_at,
        draw_text_in_box=draw_text_in_box,
        get_field_value=get_field_value,
        image_reader_cls=image_reader_cls,
        pdf_asset_log=pdf_asset_log,
        pdf_page_index=pdf_page_index,
    )

    if (
        not is_plain_order
        and safe_str(row_series.get("Customise", "")).lower() == "yes"
        and not position_has_slash
    ):

        resolved_apparel_path: Optional[Path] = None
        apparel_text = get_field_value(row_series, "Apparel Image", order_number_counts)
        if apparel_image_dir is not None or apparel_stem_map is not None:
            for name in (apparel_text, safe_str(row_series.get("Picture Name", ""))):
                if not name:
                    continue
                candidate = find_image(apparel_image_dir, name, apparel_stem_map, recursive=False)
                if candidate is not None:
                    resolved_apparel_path = candidate
                    break

        def _resolved_logo_path_for_suffix_label(slot_index: int) -> Optional[Path]:
            return logo_image_for_slot(
                slot_index,
                row_series,
                fbpi_slots=fbpi_slots,
                base_custom_path=base_custom_path,
                is_scoped_custom_merge=is_scoped_custom_merge,
                logo_customise_dir=logo_customise_dir,
                logo_custom_stem_map=logo_custom_stem_map,
                logo_normal_dir=logo_normal_dir,
                logo_normal_stem_map=logo_normal_stem_map,
                safe_str=safe_str,
                logo_design_tokens=logo_design_tokens,
                find_image_custom_exact=find_image_custom_exact,
                find_image_custom_logo=find_image_custom_logo,
                find_image_normal_logo=find_image_normal_logo,
            )

        run_logo_filename_suffix_label_step_impl(
            c,
            row_series,
            is_plain_order=is_plain_order,
            image_area_x_pt=image_area_x_pt,
            col_w_pt=col_w_pt,
            b0_y_pt=b0_y_pt,
            b1_y_pt=b1_y_pt,
            banner_h_pt=banner_h_pt,
            font_size_position=font_size_position,
            white=white,
            black=black,
            safe_str=safe_str,
            rect_at=rect_at,
            draw_text_in_box=draw_text_in_box,
            draw_rect=draw_rect,
            pt_h=pt_h,
            resolved_logo_path_for_slot=_resolved_logo_path_for_suffix_label,
            logo_design_tokens=logo_design_tokens,
            fbpi_slots=fbpi_slots,
            resolved_apparel_path=resolved_apparel_path,
            pdf_asset_log=pdf_asset_log,
            pdf_page_index=pdf_page_index,
        )
    return had_missing_logo, had_missing_apparel
