from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

from scripts.pipeline_generate_packing_list_pdf.runtime_config import BACK_PRINT_REFERENCE_IMAGE


def finalize_logo_sections_impl(
    c,
    row_series,
    order_number_counts: dict,
    *,
    is_plain_order: bool,
    fbpi_slots: List[Tuple[Path, str]],
    base_custom_path: Optional[Path],
    is_scoped_custom_merge: bool,
    logo_customise_dir: Optional[Path],
    logo_custom_stem_map: Optional[Dict[str, Path]],
    logo_normal_dir: Optional[Path],
    logo_normal_stem_map: Optional[Dict[str, Path]],
    position_has_slash: bool,
    position_code_to_draw: Optional[Dict[str, str]],
    default_position_code: str,
    position_tokens: Callable[..., list],
    ax: float,
    ay: float,
    aw: float,
    ah: float,
    image_area_x_pt: float,
    col_w_pt: float,
    s1_y_pt: float,
    s2_y_pt: float,
    square_s_pt: float,
    s2_square_h_pt: float,
    font_size_banner: float,
    black,
    red,
    logo_image_for_slot,
    draw_logo_overlays,
    draw_logo_square_rows,
    safe_str,
    logo_design_tokens,
    normalize_lower,
    find_image_custom_exact,
    find_image_custom_logo,
    find_image_normal_logo,
    prepare_image,
    rect_at,
    draw_text_in_box,
    get_field_value,
    image_reader_cls,
    pdf_asset_log: Optional[Callable[[str], None]] = None,
    pdf_page_index: int = 0,
) -> bool:
    def _logo_image_for_slot(slot_index: int) -> Optional[Path]:
        return logo_image_for_slot(
            slot_index,
            row_series,
            fbpi_slots=fbpi_slots,
            base_custom_path=base_custom_path,
            is_scoped_custom_merge=is_scoped_custom_merge,
            logo_customise_dir=logo_customise_dir,
            logo_custom_stem_map=logo_custom_stem_map,
            logo_normal_dir=logo_normal_dir,
            logo_normal_stem_map=logo_normal_stem_map,
            safe_str=safe_str,
            logo_design_tokens=logo_design_tokens,
            find_image_custom_exact=find_image_custom_exact,
            find_image_custom_logo=find_image_custom_logo,
            find_image_normal_logo=find_image_normal_logo,
        )

    has_explicit_fbpi_logo = bool(fbpi_slots)
    draw_logo_overlays(
        c,
        row_series,
        is_plain_order=is_plain_order,
        has_explicit_fbpi_logo=has_explicit_fbpi_logo,
        position_has_slash=position_has_slash,
        position_code_to_draw=position_code_to_draw,
        ax=ax,
        ay=ay,
        aw=aw,
        ah=ah,
        logo_image_for_slot=_logo_image_for_slot,
        logo_design_tokens=logo_design_tokens,
        safe_str=safe_str,
        normalize_lower=normalize_lower,
        prepare_image=prepare_image,
        image_reader_cls=image_reader_cls,
        pdf_asset_log=pdf_asset_log,
        pdf_page_index=pdf_page_index,
    )

    return draw_logo_square_rows(
        c,
        row_series,
        order_number_counts,
        is_plain_order=is_plain_order,
        image_area_x_pt=image_area_x_pt,
        col_w_pt=col_w_pt,
        s1_y_pt=s1_y_pt,
        s2_y_pt=s2_y_pt,
        square_s_pt=square_s_pt,
        s2_square_h_pt=s2_square_h_pt,
        font_size_banner=font_size_banner,
        black=black,
        red=red,
        rect_at=rect_at,
        get_field_value=get_field_value,
        logo_image_for_slot=_logo_image_for_slot,
        prepare_image=prepare_image,
        draw_text_in_box=draw_text_in_box,
        image_reader_cls=image_reader_cls,
        fbpi_slots=fbpi_slots,
        position_code_to_draw=position_code_to_draw,
        default_position_code=default_position_code,
        position_tokens=position_tokens,
        safe_str=safe_str,
        back_print_image_path=BACK_PRINT_REFERENCE_IMAGE,
        logo_design_tokens=logo_design_tokens,
        pdf_asset_log=pdf_asset_log,
        pdf_page_index=pdf_page_index,
    )
