"""Old harvest / fill spellings → canonical pick-list values."""
from __future__ import annotations

from shared.taxonomy_catalog.dims import *  # noqa: F403 — ALIASES body uses CAT_/TYPE_ tokens

ALIASES: dict[str, dict[str, str]] = {
    "category": {
        "SWEATSHIRTS AND HOODIES": CAT_SWEAT,
        "Sweatshirts And Hoodies": CAT_SWEAT,
        "Rugby Shirts": CAT_SHIRT,
        "Joggers": CAT_TROUSER,
        "Tutus": CAT_BABY,
        "Masks": CAT_ACC,
        "Badges": CAT_ACC,
        "Cards": CAT_ACC,
        "Photo Acrylic": CAT_ACC,
        "CAPS & HATS": CAT_HEAD,
        "OUTERWEAR": CAT_JACKET,
        "Hospitallity": CAT_HOSP,
        "Shirts & Blouses": CAT_SHIRT,
        "TROUSERS & JOGPANTS": CAT_TROUSER,
        "T-SHIRTS": CAT_TEE,
        "POLO SHIRTS": CAT_POLO,
        "HEADWEAR": CAT_HEAD,
    },
    "product_type": {
        "MENS SHORT SLEEVE T-SHIRT": TYPE_SS_TEE,
        "Mens Short Sleeve T-Shirt": TYPE_SS_TEE,
        "Ladies Short Sleeve T-Shirts": TYPE_SS_TEE,
        "Childrens T-Shirt": TYPE_SS_TEE,
        "Unisex T-Shirt": TYPE_SS_TEE,
        "UNISEX T-SHIRT": TYPE_SS_TEE,
        "Mens Long Sleeve T-Shirt": TYPE_LS_TEE,
        "MENS LONG SLEEVE T-SHIRTS": TYPE_LS_TEE,
        "Ladies Long Sleeve T-Shirt": TYPE_LS_TEE,
        "LADIES LONG SLEEVE T-SHIRTS": TYPE_LS_TEE,
        "Childrens Long Sleeve T-Shirt": TYPE_LS_TEE,
        "Athletic Vest": TYPE_TANK,
        "Mens Tank Tops, Vest Etc": TYPE_TANK,
        "Mens Tank Tops, Vests Etc": TYPE_TANK,
        "Ladies Vests, Camisoles, Etc.": TYPE_TANK,
        "Childrens Vest": TYPE_TANK,
        "MENS SHORT SLEEVE POLO SHIRTS": TYPE_SS_POLO,
        "Ladies Short Sleeve Polo Shirts": TYPE_SS_POLO,
        "Childrens Polo Shirt": TYPE_SS_POLO,
        "Childrens Polo Shirts": TYPE_SS_POLO,
        "Unisex Polo Shirt": TYPE_SS_POLO,
        "Unisex Polo": TYPE_SS_POLO,
        "Mens Long Sleeve Polo Shirt": TYPE_LS_POLO,
        "Mens Long Sleeve Polo Shirts": TYPE_LS_POLO,
        "Ladies Long Sleeve Polo Shirt": TYPE_LS_POLO,
        "Ladies Long Sleeve Polo Shirts": TYPE_LS_POLO,
        "Mens Sweatshirts & Hoodies": TYPE_HOODIE,
        "Ladies Sweatshirts And Hoodies": TYPE_HOODIE,
        "Childrens Sweatshirts And Hoodies": TYPE_HOODIE,
        "Unisex Sweatshirts & Hoodies": TYPE_HOODIE,
        "UNISEX SWEATSHIRTS & HOODIES": TYPE_HOODIE,
        "Unisex Sweats And Hoodies": TYPE_HOODIE,
        "Mens Woven Shirt": TYPE_SHIRT,
        "Ladies Woven Shirt": TYPE_SHIRT,
        "Childrens Woven Shirt": TYPE_SHIRT,
        "Rugby Shirt": TYPE_RUGBY,
        "Mens Jacket": TYPE_JACKET,
        "Ladies Jacket": TYPE_JACKET,
        "Childrens Jacket": TYPE_JACKET,
        "Childrens jackets": TYPE_JACKET,
        "MENS OUTER JACKETS": TYPE_JACKET,
        "Mens Fleece": TYPE_FLEECE,
        "Ladies Fleece": TYPE_FLEECE,
        "Childrens Fleece": TYPE_FLEECE,
        "Childrens Fleeces": TYPE_FLEECE,
        "Mens Trousers": TYPE_TROUSER,
        "Ladies Trousers": TYPE_TROUSER,
        "Childrens Trousers": TYPE_TROUSER,
        "Mens Trousers And Jogpants": TYPE_TROUSER,
        "Ladies Trousers And Jog Pants": TYPE_TROUSER,
        "Jog Bottoms": TYPE_JOGGER,
        "Hi-Viz T-Shirt": TYPE_HV_TEE,
        "Hi-Viz Polo Shirt": TYPE_HV_POLO,
        "Hi-Vis Trouser": TYPE_HV_TROUSER,
        "Hi-Viz Trouser": TYPE_HV_TROUSER,
        "Hi-Vis Waistcoat": TYPE_HV_VEST,
        "Hi-Vis Jacket": TYPE_HV_JACKET,
        "Safety Helmet": TYPE_HELMET,
        "Bags, Backpacks Etc": TYPE_BACKPACK,
        "T-Shirt and Hoodie": TYPE_SET,
        "Baby And Toddlerwear": TYPE_BODY,
        "Ladies Tunic": TYPE_TUNIC,
        "Mens Tunic": TYPE_TUNIC,
        "Iron-On Transfer": TYPE_IRON,
        "Baby Drawer Lock": TYPE_LOCK,
        "Photo Acrylic": TYPE_PHOTO,
    },
    "product_style": {
        "China-Bag": "China Bag",
        "Heavweight Cuffed": "Heavyweight Cuffed",
        "Softstyle Tank": "Softstyle",
        "Classic 5": "Classic 5-Panel",
        "Heavyweight 5": "Heavyweight 5-Panel",
        "Original 5": "Original 5-Panel Snapback",
        "6 Panel Low Profile": "6-Panel Low Profile",
        "25mm": "25 mm",
        "Premium V-neck": "Premium V-Neck",
        "Junior Fashion": "Junior Fashion Backpack",
        "Eco 100 Recycled Cotton": "Eco Recycled Cotton Tote",
        "T-Shirt": DEFAULT_STYLE,
        "Hoodie": DEFAULT_STYLE,
        "Sweatshirt": DEFAULT_STYLE,
        "Polo": DEFAULT_STYLE,
        "Shirt": DEFAULT_STYLE,
        "Mug": DEFAULT_STYLE,
        "Sticker": DEFAULT_STYLE,
        "Face Mask": DEFAULT_STYLE,
        "Cap": DEFAULT_STYLE,
        "Jacket": DEFAULT_STYLE,
        "Fleece": DEFAULT_STYLE,
        "Gilet": DEFAULT_STYLE,
        "Trouser": DEFAULT_STYLE,
        "Shorts": DEFAULT_STYLE,
        "Joggers": DEFAULT_STYLE,
        "Tunic": DEFAULT_STYLE,
        "Scrub": DEFAULT_STYLE,
        "Tutu": DEFAULT_STYLE,
        "Cardigan": DEFAULT_STYLE,
        "Long": "Cargo",
        "Short": "Cargo",
        "Regular": "Cargo",
        "With Knee Pad Pockets Long": "Cargo Knee Pad",
        "With Knee Pad Pockets Regular": "Cargo Knee Pad",
        "Hi-Viz Polo": "High Visibility",
        "Hi-Viz T-Shirt": "High Visibility",
        "Hi-Viz Trouser": "High Visibility",
        "Hi-Viz Waistcoat": "High Visibility",
        "Safety": "High Visibility",
        "Baseball": "Hi-Vis Baseball",
        "Heavy": "Heavy Cotton",
        "K-T": "Kids T-Shirt",
        "Iron-On": DEFAULT_STYLE,
        "Bag": DEFAULT_STYLE,
        "Apron": "Bib Apron",
        "Beanie": DEFAULT_STYLE,
        "Helmet": "Hi-Vis Baseball",
        "Badge": DEFAULT_STYLE,
        "Card": "A5",
        "Photo Acrylic": DEFAULT_STYLE,
        "Baby Drawer Lock": DEFAULT_STYLE,
        "Babywear": "Baby T-Shirt",
        "Tank": "Softstyle",
        "Vest": DEFAULT_STYLE,
        "Rugby Shirt": "Classic",
        "Tabard": "Premium",
        "Hi-Vis": "Class 2",
        "Hi-Viz Jacket": "High Visibility",
        "Long Sleeve": DEFAULT_STYLE,
        "Long Sleeve Polo": DEFAULT_STYLE,
    },
    "subcategory": {
        "Mens Short Sleeve T-Shirt": "Short Sleeve T-Shirt",
        "Ladies Short Sleeve T-Shirts": "Short Sleeve T-Shirt",
        "Childrens T-Shirt": "Short Sleeve T-Shirt",
        "Mens Long Sleeve T-Shirts": "Long Sleeve T-Shirt",
        "Mens Tank Tops, Vest Etc": "Tank Top",
        "Mens Tank Tops, Vests Etc": "Tank Top",
        "Ladies Vests, Camisoles, Etc.": "Tank Top",
        "Mens Sweatshirts & Hoodies": "Sweatshirts & Hoodies",
        "Childrens Sweatshirts And Hoodies": "Sweatshirts & Hoodies",
        "Mens Short Sleeve Polo Shirts": "Polo Shirts",
        "Bags, Backpacks Etc": "Bags",
        "Caps & Hats Etc": "Caps & Hats",
        "Aprons And Tabards": "Aprons & Tabards",
    },
    "department": {},
}
