"""Supplier-code → style / bag-type / head-type lookups."""
from __future__ import annotations

from shared.taxonomy_catalog.dims import (  # noqa: F401 — maps reference TYPE_* / DEFAULT_STYLE
    DEFAULT_STYLE,
    TYPE_BACKPACK,
    TYPE_BAG_ACC,
    TYPE_BARREL,
    TYPE_BEANIE,
    TYPE_BOOK,
    TYPE_CAP,
    TYPE_DRAWSTRING,
    TYPE_GYMSAC,
    TYPE_LUNCH,
    TYPE_PENCIL,
    TYPE_TOTE,
)

STYLE_BY_CODE: dict[str, str] = {
    "5000": "Heavy Cotton",
    "G5000": "Heavy Cotton",
    "2400": "Ultra Cotton",
    "61026": "Valueweight Baseball",
    "61033": "Valueweight",
    "61168": "Ringer",
    "64200": "Softstyle",
    "64200L": "Softstyle",
    "64800": "Softstyle Double Pique",
    "85800L": "Premium Cotton Polo",
    "AA77": "Bib Apron",
    "B10B": "Junior Original 5-Panel Cap",
    "B445": "Original Patch",
    "B610C": "5-Panel Contrast Snapback",
    "B641": "Patch Snapback Trucker",
    "BG10": "Premium Gymsac",
    "BG125": "Original Fashion Backpack",
    "BG125J": "Junior Fashion Backpack",
    "BG125L": "Maxi Fashion Backpack",
    "BG125S": "Mini Fashion Backpack",
    "BG14": "Retro Shoulder Bag",
    "BG140S": "Mini Barrel Bag",
    "BG145": "Junior Dance Bag",
    "BG150": "Packaway Barrel Bag",
    "BG153": "Mini Essential Fashion Backpack",
    "BG38": "Grab Pouch",
    "BG40": "Ripper Wallet",
    "BG42": "Belt Bag",
    "BG5": "Budget Gymsac",
    "BG542": "Athleisure Gymsac",
    "BG728": "Felt Trug",
    "BG745": "Boutique Circular Key Clip",
    "BG750": "Boutique Accessory Pouch",
    "BZ02": "Baby T-Shirt",
    "BZ10": "Baby Bodysuit",
    "C2200": "Ringspun Blended",
    "C2400": "Ringspun Blended",
    "C800T": "Baby Body Suit",
    "C8030T": "Baby Romper",
    "CA3001T": "Toddler Jersey",
    "HVW801": "Executive Vest",
    "JC003": "Contrast Cool",
    "JC03J": "Contrast Cool",
    "JH001": "College",
    "JH01J": "College",
    "M61": "Ceramic Mug",
    "QD435": "Lunch Cooler",
    "QD440": "Water Bottle Holder",
    "QD442": "Pencil Case",
    "QD452": "Enhanced-Viz Book Bag",
    "QD456": "Classic Book Bag",
    "QD457": "Junior Book Bag With Strap",
    "QD51": "Junior Book Bag",
    "QD76": "Teamwear Shoe Bag",
    "QD85": "Hiking Boot Bag",
    "QD86": "Boot Bag",
    "RC05J": "Junior Cotton Cap",
    "RC80X": "Houston 5-Panel Printers Cap",
    "SF500B": "Softstyle Midweight Fleece",
    "SH1808": "Sandwich Lunchbox",
    "SH4112": "Guildford Cotton Tote",
    "SH5891": "Stafford Contrast Drawstring",
    "TD02B": "Kids Tie Dye",
    "TPC001": "Cotton Tote",
    "UCC003": "Everyday Polo",
    "W101": "Bag For Life",
    "W101S": "Bag For Life Short Handles",
    "W110": "Cotton Gymsac",
    "W115": "Cotton Stuff Bag",
    "W121": "Cotton Ribbon Cord Bag",
    "W201": "Premium Cotton Tote",
    "W265": "Organic Premium Maxi Tote",
    "W350": "Cotton Cushion Cover",
    "W364": "Cotton Adult Apron",
    "W407": "Jute Classic Shopper",
    "W415": "Jute Stuff Bag",
    "W422": "Printers Jute Shopper",
    "W425": "Pocket Jute Gift Bag",
    "W426": "Pocket Jute Midi Tote",
    "W427": "Cotton Pocket Jute Shopper",
    "W450": "Jute Base Canvas Shopper",
    "W451": "Jute Base Canvas Tote",
    "W452": "Jute Base Canvas Tote XL",
    "W530": "Canvas Accessory Case",
    "W540": "Canvas Accessory Bag",
    "W544": "Canvas Accessory Bag",
    "W552": "Canvas Accessory Case",
    "W600": "Gallery Canvas Tote",
    "W620": "Fairtrade Cotton Bottle Bag",
    "W680": "Nautical Beach Bag",
    "W696": "Oversized Canvas Tote",
    "W825": "Organic Spring Purse",
    "W830": "Organic Accessory Pouch",
    "W858": "EarthAware Contrast Shopper",
    "6M014V": DEFAULT_STYLE,
}

BAG_TYPE_BY_CODE: dict[str, str] = {
    "BG10": TYPE_GYMSAC,
    "BG125": TYPE_BACKPACK,
    "BG125J": TYPE_BACKPACK,
    "BG125L": TYPE_BACKPACK,
    "BG125S": TYPE_BACKPACK,
    "BG14": TYPE_BAG_ACC,
    "BG140S": TYPE_BARREL,
    "BG145": TYPE_BARREL,
    "BG150": TYPE_BARREL,
    "BG153": TYPE_BACKPACK,
    "BG38": TYPE_BAG_ACC,
    "BG40": TYPE_BAG_ACC,
    "BG42": TYPE_BAG_ACC,
    "BG5": TYPE_GYMSAC,
    "BG542": TYPE_GYMSAC,
    "BG728": TYPE_BAG_ACC,
    "BG745": TYPE_BAG_ACC,
    "BG750": TYPE_BAG_ACC,
    "QD435": TYPE_LUNCH,
    "QD440": TYPE_BAG_ACC,
    "QD442": TYPE_PENCIL,
    "QD452": TYPE_BOOK,
    "QD456": TYPE_BOOK,
    "QD457": TYPE_BOOK,
    "QD51": TYPE_BOOK,
    "QD76": TYPE_BAG_ACC,
    "QD85": TYPE_BAG_ACC,
    "QD86": TYPE_BAG_ACC,
    "SH1808": TYPE_LUNCH,
    "SH4112": TYPE_TOTE,
    "SH5891": TYPE_DRAWSTRING,
    "TPC001": TYPE_TOTE,
    "W101": TYPE_TOTE,
    "W101S": TYPE_TOTE,
    "W110": TYPE_GYMSAC,
    "W115": TYPE_BAG_ACC,
    "W121": TYPE_TOTE,
    "W201": TYPE_TOTE,
    "W265": TYPE_TOTE,
    "W350": TYPE_BAG_ACC,
    "W407": TYPE_TOTE,
    "W415": TYPE_BAG_ACC,
    "W422": TYPE_TOTE,
    "W425": TYPE_BAG_ACC,
    "W426": TYPE_TOTE,
    "W427": TYPE_TOTE,
    "W450": TYPE_TOTE,
    "W451": TYPE_TOTE,
    "W452": TYPE_TOTE,
    "W530": TYPE_BAG_ACC,
    "W540": TYPE_BAG_ACC,
    "W544": TYPE_BAG_ACC,
    "W552": TYPE_BAG_ACC,
    "W600": TYPE_TOTE,
    "W620": TYPE_BAG_ACC,
    "W680": TYPE_TOTE,
    "W696": TYPE_TOTE,
    "W825": TYPE_BAG_ACC,
    "W830": TYPE_BAG_ACC,
    "W858": TYPE_TOTE,
}

HEAD_TYPE_BY_CODE: dict[str, str] = {
    "B10B": TYPE_CAP,
    "B445": TYPE_BEANIE,
    "B610C": TYPE_CAP,
    "B641": TYPE_CAP,
    "RC05J": TYPE_CAP,
    "RC80X": TYPE_CAP,
}
