"""Styles that duplicate the product type — collapse to Standard."""
from __future__ import annotations

TYPE_DUPLICATE_STYLES = frozenset(
    {
        "T-Shirt",
        "T Shirt",
        "Hoodie",
        "Sweatshirt",
        "Polo",
        "Polo Shirt",
        "Shirt",
        "Trouser",
        "Trousers",
        "Jacket",
        "Fleece",
        "Gilet",
        "Cap",
        "Beanie",
        "Mug",
        "Sticker",
        "Apron",
        "Tunic",
        "Scrub",
        "Tabard",
        "Tutu",
        "Cardigan",
        "Joggers",
        "Shorts",
        "Face Mask",
        "Badge",
        "Card",
        "Photo Acrylic",
        "Iron-On",
        "Bag",
        "Babywear",
        "Vest",
        "Tank",
        "Helmet",
        "Hi-Vis",
        "Hi-Viz",
        "Hi-Viz Polo",
        "Hi-Viz T-Shirt",
        "Hi-Viz Trouser",
        "Hi-Viz Waistcoat",
        "Hi-Viz Jacket",
        "Long",
        "Short",
        "Regular",
        "Long Sleeve",
        "Long Sleeve Polo",
        "Softstyle Tank",
    }
)
