"""Closed Product Style (Areeb) pick-list values."""
from __future__ import annotations

from shared.taxonomy_catalog.dims import DEFAULT_STYLE

PRODUCT_STYLES = (
    DEFAULT_STYLE,
    "Valueweight",
    "Valueweight Baseball",
    "Iconic 150",
    "Original",
    "Heavy Cotton",
    "Softstyle",
    "Ultra Cotton",
    "Heavy Blend",
    "Softstyle Midweight Fleece",
    "Classic",
    "Deluxe",
    "Premium",
    "The UX",
    "Eco",
    "Contrast",
    "Olympic",
    "Active",
    "Heavyweight",
    "Ultra Cool",
    "Super Cool Workwear",
    "Super Pro",
    "Cotton Rich",
    "Ultimate Cotton",
    "Polycotton Workwear",
    "Eco Workwear",
    "Processable",
    "Jersey",
    "Sports",
    "Two Tone",
    "Action",
    "Workwear",
    "Cargo",
    "Cargo Knee Pad",
    "Lightweight",
    "Premium Reversible",
    "Reversible",
    "Premium V-Neck",
    "Classic V-Neck",
    "V-Neck",
    "Ringer",
    "Acid Wash Vintage Rust",
    "Acid Wash Optic Wash",
    "High Visibility",
    "Class 2",
    "Sleeveless Safety",
    "Executive Vest",
    "Hi-Vis Baseball",
    "College",
    "Contrast Cool",
    "Ringspun Blended",
    "Everyday Polo",
    "Softstyle Double Pique",
    "Premium Cotton Polo",
    "Toddler Jersey",
    "Kids Tie Dye",
    "Baby Body Suit",
    "Baby Romper",
    "Baby T-Shirt",
    "Baby Bodysuit",
    "Poplin",
    "Pinpoint Oxford",
    "Quarter Zip",
    "Printable Softshell",
    "Microfleece",
    "Padded",
    "Outdoor",
    "Road Safety",
    "Original Patch",
    "Snowstar Patch",
    "Circular Patch",
    "Rectangular Patch",
    "Pom Pom",
    "Heavyweight Cuffed",
    "6-Panel Low Profile",
    "Classic 5-Panel",
    "Heavyweight 5-Panel",
    "Original 5-Panel Snapback",
    "Snapback Trucker",
    "5-Panel Contrast Snapback",
    "Patch Snapback Trucker",
    "Junior Original 5-Panel Cap",
    "Junior Cotton Cap",
    "Houston 5-Panel Printers Cap",
    "Fairtrade Cotton Junior",
    "Bib With Pocket",
    "Bib Apron",
    "Cotton Adult Apron",
    "Kids Set",
    "A3",
    "A4",
    "A5",
    "A6",
    "Circle",
    "25 mm",
    "Ceramic Mug",
    "Kids T-Shirt",
    "China Bag",
    "Cotton Shopper",
    "Eco Recycled Cotton Tote",
    "Junior Fashion Backpack",
    "Original Fashion Backpack",
    "Maxi Fashion Backpack",
    "Mini Fashion Backpack",
    "Mini Essential Fashion Backpack",
    "Premium Gymsac",
    "Budget Gymsac",
    "Athleisure Gymsac",
    "Cotton Gymsac",
    "Retro Shoulder Bag",
    "Mini Barrel Bag",
    "Packaway Barrel Bag",
    "Junior Dance Bag",
    "Grab Pouch",
    "Ripper Wallet",
    "Belt Bag",
    "Felt Trug",
    "Boutique Circular Key Clip",
    "Boutique Accessory Pouch",
    "Boutique Wristlet Keyring",
    "Lunch Cooler",
    "Water Bottle Holder",
    "Pencil Case",
    "Enhanced-Viz Book Bag",
    "Classic Book Bag",
    "Junior Book Bag",
    "Junior Book Bag With Strap",
    "Teamwear Shoe Bag",
    "Hiking Boot Bag",
    "Boot Bag",
    "Sandwich Lunchbox",
    "Guildford Cotton Tote",
    "Stafford Contrast Drawstring",
    "Cotton Tote",
    "Bag For Life",
    "Bag For Life Short Handles",
    "Cotton Stuff Bag",
    "Cotton Ribbon Cord Bag",
    "Premium Cotton Tote",
    "Organic Premium Maxi Tote",
    "Cotton Cushion Cover",
    "Jute Classic Shopper",
    "Jute Stuff Bag",
    "Printers Jute Shopper",
    "Pocket Jute Gift Bag",
    "Pocket Jute Midi Tote",
    "Cotton Pocket Jute Shopper",
    "Jute Base Canvas Shopper",
    "Jute Base Canvas Tote",
    "Jute Base Canvas Tote XL",
    "Canvas Accessory Case",
    "Canvas Accessory Bag",
    "Gallery Canvas Tote",
    "Fairtrade Cotton Bottle Bag",
    "Nautical Beach Bag",
    "Oversized Canvas Tote",
    "Organic Spring Purse",
    "Organic Accessory Pouch",
    "EarthAware Contrast Shopper",
)
