"""Phrase needles → canonical Product Style names."""
from __future__ import annotations

STYLE_PHRASES: tuple[tuple[str, str], ...] = (
    ("softstyle midweight fleece", "Softstyle Midweight Fleece"),
    ("softstyle midw fleece", "Softstyle Midweight Fleece"),
    ("cargo trouser with knee pad pockets", "Cargo Knee Pad"),
    ("with knee pad pockets", "Cargo Knee Pad"),
    ("fairtrade cotton junior", "Fairtrade Cotton Junior"),
    ("eco 100 recycled cotton", "Eco Recycled Cotton Tote"),
    ("acid wash vintage rust", "Acid Wash Vintage Rust"),
    ("acid wash optic wash", "Acid Wash Optic Wash"),
    ("boutique wristlet keyring", "Boutique Wristlet Keyring"),
    ("premium reversible", "Premium Reversible"),
    ("super cool workwear", "Super Cool Workwear"),
    ("polycotton workwear", "Polycotton Workwear"),
    ("pinpoint oxford", "Pinpoint Oxford"),
    ("classic v neck", "Classic V-Neck"),
    ("classic v-neck", "Classic V-Neck"),
    ("premium v-neck", "Premium V-Neck"),
    ("premium v neck", "Premium V-Neck"),
    ("6 panel low profile", "6-Panel Low Profile"),
    ("heavyweight 5 panel", "Heavyweight 5-Panel"),
    ("original snapback 5 panel", "Original 5-Panel Snapback"),
    ("classic 5 panel", "Classic 5-Panel"),
    ("heavweight cuffed", "Heavyweight Cuffed"),
    ("heavyweight cuffed", "Heavyweight Cuffed"),
    ("sleeveless safety", "Sleeveless Safety"),
    ("high visibility", "High Visibility"),
    ("original patch", "Original Patch"),
    ("snowstar patch", "Snowstar Patch"),
    ("circular patch", "Circular Patch"),
    ("rectangular patch", "Rectangular Patch"),
    ("bib apron with pocket", "Bib With Pocket"),
    ("bib with pocket", "Bib With Pocket"),
    ("cotton shopper", "Cotton Shopper"),
    ("china bag", "China Bag"),
    ("china-bag", "China Bag"),
    ("junior fashion backpack", "Junior Fashion Backpack"),
    ("printable softshell", "Printable Softshell"),
    ("printable soft shell", "Printable Softshell"),
    ("quarter zip", "Quarter Zip"),
    ("1/4 zip", "Quarter Zip"),
    ("eco workwear", "Eco Workwear"),
    ("cotton rich", "Cotton Rich"),
    ("ultimate cotton", "Ultimate Cotton"),
    ("ultra cotton", "Ultra Cotton"),
    ("ultra cool", "Ultra Cool"),
    ("heavy cotton", "Heavy Cotton"),
    ("heavy blend", "Heavy Blend"),
    ("iconic 150", "Iconic 150"),
    ("the ux", "The UX"),
    ("super pro", "Super Pro"),
    ("class 2", "Class 2"),
    ("pom pom", "Pom Pom"),
    ("snapback trucker", "Snapback Trucker"),
    ("road safety", "Road Safety"),
    ("kids set", "Kids Set"),
    ("valueweight", "Valueweight"),
    ("softstyle", "Softstyle"),
    ("heavyweight", "Heavyweight"),
    ("lightweight", "Lightweight"),
    ("reversible", "Reversible"),
    ("processable", "Processable"),
    ("two tone", "Two Tone"),
    ("microfleece", "Microfleece"),
    ("micro fleece", "Microfleece"),
    ("bodywarmer", "Padded"),
    ("body warmer", "Padded"),
    ("padded", "Padded"),
    ("outdoor", "Outdoor"),
    ("ringer", "Ringer"),
    ("classic", "Classic"),
    ("deluxe", "Deluxe"),
    ("premium", "Premium"),
    ("olympic", "Olympic"),
    ("active", "Active"),
    ("contrast", "Contrast"),
    ("jersey", "Jersey"),
    ("sports", "Sports"),
    ("original", "Original"),
    ("workwear", "Workwear"),
    ("action", "Action"),
    ("cargo", "Cargo"),
    ("poplin", "Poplin"),
    ("eco", "Eco"),
    ("v neck", "V-Neck"),
    ("v-neck", "V-Neck"),
)
