"""Exact Gender Apparel → warehouse 4-tuple overrides."""
from __future__ import annotations

import shared.taxonomy_catalog as tax
from shared.areeb_taxonomy.consts import (
    GENDER_GENERAL,
    GENDER_KIDS,
    GENDER_MENS,
    GENDER_UNISEX,
    GENDER_WOMENS,
)

# Exact Gender Apparel → warehouse 4-tuple. Overrides the pattern engine.
# Tuple: Category, Product Type, Product Style, Department (gender only).
CL_STANDARD_RULES: dict[str, tuple[str, str, str, str]] = {
    "Mens-T-Shirt": (tax.CAT_TEE, tax.TYPE_SS_TEE, tax.DEFAULT_STYLE, GENDER_MENS),
    "Womens-T-Shirt": (tax.CAT_TEE, tax.TYPE_SS_TEE, tax.DEFAULT_STYLE, GENDER_WOMENS),
    "Kids-T-Shirt": (tax.CAT_TEE, tax.TYPE_SS_TEE, tax.DEFAULT_STYLE, GENDER_KIDS),
    "GILDAN Heavy Cotton Adult T-Shirt": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Heavy Cotton", GENDER_MENS),
    "GILDAN Softstyle Adult T-Shirt": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Softstyle", GENDER_MENS),
    "GILDAN Softstyle Ladies T Shirt": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Softstyle", GENDER_WOMENS),
    "GILDAN Softstyle Ladies Tank Top": (tax.CAT_TEE, tax.TYPE_TANK, "Softstyle", GENDER_WOMENS),
    "FOTL Kids Valueweight T": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Valueweight", GENDER_KIDS),
    "5000": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Heavy Cotton", GENDER_MENS),
    "G5000": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Heavy Cotton", GENDER_MENS),
    "2400": (tax.CAT_TEE, tax.TYPE_LS_TEE, "Ultra Cotton", GENDER_MENS),
    "61026": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Valueweight Baseball", GENDER_MENS),
    "61168-Ringer": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Ringer", GENDER_MENS),
    "TD02B": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Kids Tie Dye", GENDER_KIDS),
    "CA3001T": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Toddler Jersey", GENDER_KIDS),
    "JC003": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Contrast Cool", GENDER_MENS),
    "JC03J": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Contrast Cool", GENDER_KIDS),
    "Acid Wash Vintage Rust": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Acid Wash Vintage Rust", GENDER_MENS),
    "Acid Wash Optic Wash": (tax.CAT_TEE, tax.TYPE_SS_TEE, "Acid Wash Optic Wash", GENDER_MENS),
    "Mens-Hoodie": (tax.CAT_SWEAT, tax.TYPE_HOODIE, tax.DEFAULT_STYLE, GENDER_MENS),
    "Mens-Sweatshirt": (tax.CAT_SWEAT, tax.TYPE_SWEAT, tax.DEFAULT_STYLE, GENDER_MENS),
    "Womens-Hoodie": (tax.CAT_SWEAT, tax.TYPE_HOODIE, tax.DEFAULT_STYLE, GENDER_WOMENS),
    "Womens-Sweatshirt": (tax.CAT_SWEAT, tax.TYPE_SWEAT, tax.DEFAULT_STYLE, GENDER_WOMENS),
    "Kids-Hoodie": (tax.CAT_SWEAT, tax.TYPE_HOODIE, tax.DEFAULT_STYLE, GENDER_KIDS),
    "Kids-Sweatshirt": (tax.CAT_SWEAT, tax.TYPE_SWEAT, tax.DEFAULT_STYLE, GENDER_KIDS),
    "GILDAN Heavy Blend Adult Hooded Sweatshirt": (tax.CAT_SWEAT, tax.TYPE_HOODIE, "Heavy Blend", GENDER_MENS),
    "GILDAN Softstyle Midw Fleece Youth Hoodie": (
        tax.CAT_SWEAT,
        tax.TYPE_HOODIE,
        "Softstyle Midweight Fleece",
        GENDER_KIDS,
    ),
    "GILDAN Softstyle Midweight Fleece Youth Hoodie": (
        tax.CAT_SWEAT,
        tax.TYPE_HOODIE,
        "Softstyle Midweight Fleece",
        GENDER_KIDS,
    ),
    "JH001-Hoodie": (tax.CAT_SWEAT, tax.TYPE_HOODIE, "College", GENDER_MENS),
    "JH01J-Hoodie": (tax.CAT_SWEAT, tax.TYPE_HOODIE, "College", GENDER_KIDS),
    "C2200-Hoodie": (tax.CAT_SWEAT, tax.TYPE_HOODIE, "Ringspun Blended", GENDER_MENS),
    "C2400": (tax.CAT_SWEAT, tax.TYPE_SWEAT, "Ringspun Blended", GENDER_MENS),
    "SF500B-Hoodie": (tax.CAT_SWEAT, tax.TYPE_HOODIE, "Softstyle Midweight Fleece", GENDER_KIDS),
    "Kids-T-Shirt-Hoodie": (tax.CAT_SETS, tax.TYPE_SET, "Kids Set", GENDER_KIDS),
    "85800L-Polo-T-Shirt": (tax.CAT_POLO, tax.TYPE_SS_POLO, "Premium Cotton Polo", GENDER_WOMENS),
    "64800-Polo T-Shirt": (tax.CAT_POLO, tax.TYPE_SS_POLO, "Softstyle Double Pique", GENDER_MENS),
    "UCC003-Mens-Polo": (tax.CAT_POLO, tax.TYPE_SS_POLO, "Everyday Polo", GENDER_MENS),
    "Uneek Hi-Viz Polo Shirt": (tax.CAT_POLO, tax.TYPE_HV_POLO, "High Visibility", GENDER_UNISEX),
    "64200": (tax.CAT_TEE, tax.TYPE_TANK, "Softstyle", GENDER_MENS),
    "64200L": (tax.CAT_TEE, tax.TYPE_TANK, "Softstyle", GENDER_WOMENS),
    "C800T-BS": (tax.CAT_BABY, tax.TYPE_BODY, "Baby Body Suit", GENDER_KIDS),
    "C8030T-BS": (tax.CAT_BABY, tax.TYPE_ROMPER, "Baby Romper", GENDER_KIDS),
    "BZ02-Toddler-T-Shirt": (tax.CAT_BABY, tax.TYPE_BABY_TEE, "Baby T-Shirt", GENDER_KIDS),
    "BZ10-Body Suit": (tax.CAT_BABY, tax.TYPE_BODY, "Baby Bodysuit", GENDER_KIDS),
    "Kids-Toddler 61033": (tax.CAT_BABY, tax.TYPE_BABY_TEE, "Valueweight", GENDER_KIDS),
    "China Bag": (tax.CAT_BAGS, tax.TYPE_TOTE, "China Bag", GENDER_GENERAL),
    "Cotton-Shopper": (tax.CAT_BAGS, tax.TYPE_TOTE, "Cotton Shopper", GENDER_GENERAL),
    "BagBase Boutique Wristlet Keyring": (
        tax.CAT_BAGS,
        tax.TYPE_BAG_ACC,
        "Boutique Wristlet Keyring",
        GENDER_GENERAL,
    ),
    "PC-QD442": (tax.CAT_BAGS, tax.TYPE_PENCIL, "Pencil Case", GENDER_GENERAL),
    "WB-QD440": (tax.CAT_BAGS, tax.TYPE_BAG_ACC, "Water Bottle Holder", GENDER_GENERAL),
    "W696": (tax.CAT_BAGS, tax.TYPE_TOTE, "Oversized Canvas Tote", GENDER_GENERAL),
    "W265": (tax.CAT_BAGS, tax.TYPE_TOTE, "Organic Premium Maxi Tote", GENDER_GENERAL),
    "BG745": (tax.CAT_BAGS, tax.TYPE_BAG_ACC, "Boutique Circular Key Clip", GENDER_GENERAL),
    "Yoko Hi-Vis Class 2 Waistcoat": (tax.CAT_SAFETY, tax.TYPE_HV_VEST, "Class 2", GENDER_UNISEX),
    "Hi-Vis-HVW801": (tax.CAT_SAFETY, tax.TYPE_HV_VEST, "Executive Vest", GENDER_UNISEX),
    "Beechfield Original Patch Beanie": (tax.CAT_HEAD, tax.TYPE_BEANIE, "Original Patch", GENDER_GENERAL),
    "Beechfield Snowstar Patch Beanie": (tax.CAT_HEAD, tax.TYPE_BEANIE, "Snowstar Patch", GENDER_GENERAL),
    "BEECH Original Patch Beanie": (tax.CAT_HEAD, tax.TYPE_BEANIE, "Original Patch", GENDER_GENERAL),
    "BEECH Snowstar Patch Beanie": (tax.CAT_HEAD, tax.TYPE_BEANIE, "Snowstar Patch", GENDER_GENERAL),
    "Cap-B445": (tax.CAT_HEAD, tax.TYPE_BEANIE, "Original Patch", GENDER_GENERAL),
    "Cap-B641": (tax.CAT_HEAD, tax.TYPE_CAP, "Patch Snapback Trucker", GENDER_GENERAL),
    "Westford Mill FairTrade Cotton Junior Apron": (
        tax.CAT_HOSP,
        tax.TYPE_APRON,
        "Fairtrade Cotton Junior",
        GENDER_KIDS,
    ),
    "WFMILL FairTrade Cotton Junior Apron": (
        tax.CAT_HOSP,
        tax.TYPE_APRON,
        "Fairtrade Cotton Junior",
        GENDER_KIDS,
    ),
    "AA77-Apron": (tax.CAT_HOSP, tax.TYPE_APRON, "Bib Apron", GENDER_GENERAL),
    "W364-Apron": (tax.CAT_HOSP, tax.TYPE_APRON, "Cotton Adult Apron", GENDER_GENERAL),
    "Sticker": (tax.CAT_STICKER, tax.TYPE_STICKER, tax.DEFAULT_STYLE, GENDER_GENERAL),
    "Stickers": (tax.CAT_STICKER, tax.TYPE_STICKER, "Circle", GENDER_GENERAL),
    "STICKER": (tax.CAT_STICKER, tax.TYPE_STICKER, "A4", GENDER_GENERAL),
    "Mug": (tax.CAT_MUGS, tax.TYPE_MUG, tax.DEFAULT_STYLE, GENDER_GENERAL),
    "Mug-M61": (tax.CAT_MUGS, tax.TYPE_MUG, "Ceramic Mug", GENDER_GENERAL),
    "Mask": (tax.CAT_ACC, tax.TYPE_MASK, tax.DEFAULT_STYLE, GENDER_GENERAL),
    "6M014V": (tax.CAT_ACC, tax.TYPE_MASK, tax.DEFAULT_STYLE, GENDER_GENERAL),
    "Badge": (tax.CAT_ACC, tax.TYPE_BADGE, "25 mm", GENDER_GENERAL),
    "Card": (tax.CAT_ACC, tax.TYPE_CARD, "A5", GENDER_GENERAL),
    "Photo Acrylic": (tax.CAT_ACC, tax.TYPE_PHOTO, tax.DEFAULT_STYLE, GENDER_GENERAL),
    "Baby Drawer Lock": (tax.CAT_ACC, tax.TYPE_LOCK, tax.DEFAULT_STYLE, GENDER_GENERAL),
    "Only-Design": (tax.CAT_IRON, tax.TYPE_IRON, tax.DEFAULT_STYLE, GENDER_GENERAL),
    "Kids-Tutu": (tax.CAT_BABY, tax.TYPE_TUTU, tax.DEFAULT_STYLE, GENDER_KIDS),
}

CL_LEFTOVER_RULES = CL_STANDARD_RULES
CL_STANDARD_RULES_FOLD = {k.casefold(): v for k, v in CL_STANDARD_RULES.items()}
CL_LEFTOVER_RULES_FOLD = CL_STANDARD_RULES_FOLD
