"""Phrase tables for Gender Apparel pattern classification."""
from __future__ import annotations

import re

import shared.taxonomy_catalog as tax

_NON_APPAREL = frozenset(
    {
        tax.CAT_BAGS,
        tax.CAT_IRON,
        tax.CAT_STICKER,
        tax.CAT_MUGS,
        tax.CAT_ACC,
        tax.CAT_HEAD,
        tax.CAT_HOSP,
    }
)

_GARMENT_PHRASES = tuple(
    sorted(
        (
            "full zip hooded sweatshirt",
            "full zip micro fleece jacket",
            "full zip microfleece jacket",
            "full zip fleece jacket",
            "full zip soft shell jacket",
            "full zip softshell jacket",
            "full zip fleece",
            "quarter zip microfleece jacket",
            "quarter zip sweatshirt",
            "1/4 zip micro fleece jacket",
            "hooded sweatshirt",
            "crewneck sweatshirt",
            "crew neck sweatshirt",
            "crew neck t-shirt",
            "crew neck t shirt",
            "long sleeve baseball t-shirt",
            "long sleeve poplin shirt",
            "short sleeve poplin shirt",
            "long sleeve t-shirt",
            "long sleeve t shirt",
            "hi viz short sleeve polo shirt",
            "hi-viz short sleeve polo shirt",
            "hi viz short sleeve t shirt",
            "hi-viz short sleeve t shirt",
            "hi-viz polo shirt",
            "hi viz polo shirt",
            "hi-vis class 2 waistcoat",
            "hi-vis baseball safety helmet",
            "childrens hi-viz waist coat",
            "printable softshell gilet",
            "printable soft shell jacket",
            "padded bodywarmer",
            "body warmer",
            "waist coat",
            "waistcoat",
            "athletic vest",
            "tank top",
            "polo shirt",
            "poloshirt",
            "t-shirt",
            "t shirt",
            "sweat jacket",
            "sweatshirt",
            "crewneck",
            "hoodie",
            "hooded",
            "softshell jacket",
            "soft shell jacket",
            "outdoor jacket",
            "fleece jacket",
            "active jacket",
            "bomber jacket",
            "road safety jacket",
            "safety helmet",
            "jogging pants",
            "jog bottoms",
            "cargo shorts",
            "cargo trousers",
            "cargo trouser",
            "trouser regular",
            "trouser long",
            "trouser short",
            "trousers",
            "trouser",
            "rugby shirt",
            "body suit",
            "bodysuit",
            "baseball t-shirt",
            "ringer t",
            "poplin full sleeve shirt",
            "poplin half sleeve shirt",
            "pinpoint oxford full sleeve shirt",
            "pinpoint oxford half sleeve shirt",
            "full sleeve shirt",
            "half sleeve shirt",
            "longsleeve poloshirt",
            "long sleeve",
            "short sleeve",
            "full zip",
            "quarter zip",
            "microfleece",
            "micro fleece",
            "softshell",
            "soft shell",
            "cardigan",
            "gilet",
            "jacket",
            "fleece",
            "beanie",
            "beanies",
            "snapback",
            "trucker cap",
            "dad cap",
            "panel cap",
            "apron",
            "tunic",
            "tabard",
            "scrub",
            "shorts",
            "polo",
            "vest",
            "shirt",
            "tote bag",
            "backpack",
            "shopper",
            "keyring",
            "helmet",
            "mask",
            "mug",
            "sticker",
            "stickers",
            "tutu",
            "bag",
        ),
        key=len,
        reverse=True,
    )
)

_KIND_STYLE = {
    "ironon": tax.DEFAULT_STYLE,
    "bag": tax.DEFAULT_STYLE,
    "cap": tax.DEFAULT_STYLE,
    "beanie": tax.DEFAULT_STYLE,
    "helmet": "Hi-Vis Baseball",
    "sticker": tax.DEFAULT_STYLE,
    "mug": tax.DEFAULT_STYLE,
    "mask": tax.DEFAULT_STYLE,
    "badge": "25 mm",
    "card": "A5",
    "photo": tax.DEFAULT_STYLE,
    "lock": tax.DEFAULT_STYLE,
    "tutu": tax.DEFAULT_STYLE,
    "apron": tax.DEFAULT_STYLE,
    "tee_hoodie": "Kids Set",
    "baby": "Baby Body Suit",
    "hi_viz_polo": "High Visibility",
    "hi_viz_tee": "High Visibility",
    "hi_viz_trouser": "High Visibility",
    "hi_viz_waistcoat": "High Visibility",
    "hi_viz_jacket": "High Visibility",
    "hi_vis": "High Visibility",
    "hoodie": tax.DEFAULT_STYLE,
    "sweatshirt": tax.DEFAULT_STYLE,
    "tee": tax.DEFAULT_STYLE,
    "long_sleeve": tax.DEFAULT_STYLE,
    "tank": tax.DEFAULT_STYLE,
    "vest": tax.DEFAULT_STYLE,
    "polo": tax.DEFAULT_STYLE,
    "long_polo": tax.DEFAULT_STYLE,
    "woven": tax.DEFAULT_STYLE,
    "trouser": tax.DEFAULT_STYLE,
    "shorts": tax.DEFAULT_STYLE,
    "jogger": tax.DEFAULT_STYLE,
    "jacket": tax.DEFAULT_STYLE,
    "fleece": tax.DEFAULT_STYLE,
    "gilet": tax.DEFAULT_STYLE,
    "cardigan": tax.DEFAULT_STYLE,
    "rugby": "Classic",
    "tunic": tax.DEFAULT_STYLE,
    "scrub": tax.DEFAULT_STYLE,
    "tabard": "Premium",
}

_CODE_RE = re.compile(r"[A-Za-z]{0,6}\d+[A-Za-z]{0,4}")
_IRON_SIZES = frozenset({"A3", "A4", "A5", "A6"})
